<<<<<<< HEAD
[tool.poetry]
name = "blends"
version = "0.1.0"
description = ""
authors = ["Alessio Tamburro"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.1"
ipykernel = "^6.29.3"
python-dotenv = "^1.0.1"
openai = "^1.14.3"
streamlit = "^1.32.2"
langchain = "^0.1.13"
langchain-community = "^0.0.29"
graphviz = "^0.20.3"
scikit-learn = "^1.4.1.post1"
plotly = "^5.20.0"
umap-learn = "^0.5.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
=======
>>>>>>> 6d34981d31e1cc9e5f335c48a2fbbdfd768c7242
